navbar_entries:
  - title: Home
    url: /index
  - title: Post list
    url: /posts
  - title: About me
    url: /about

project_entries:
  - title: Lego robot arm
    url: 2024/10/19/Lego-Arm
    desc: Stacking Legos autonomously
    highlight: FEATURED
  
  - title: vSLAM with DL
    url: 2024/10/19/Independent-Study
    desc: Feature detection with neural networks for vSLAM
    highlight: FEATURED
  
  - title: server1-5
    url: 2024/08/12/server1-5
    desc: Homemade servers from old laptops

  - title: PN-API
    url: 2024/08/12/PN-API
    desc: Online anonymity, customizable and free
    highlight: REVIVED

footer_entries:
  - title: <i class="fa-brands fa-github"></i>
    url: https://github.com/snapwhiz914

  - title: <i class="fa-solid fa-rss"></i>
    url: feed.xml